name: ubuntu-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.8.0'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          modules: 'qt5compat qtcharts'
      - name: dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - name: build
        env:
          CC: gcc-9
          CXX: g++-9
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ../src
          cmake --build .
