name: macos-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.8.0'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qt5compat qtcharts'
      - name: dependencies
        run: |
          brew update
          brew install boost
          brew install glfw3 
          brew install glew
      - name: build
        run: |
          cd external/GKLib
          make config prefix=./install-Darwin
          make install
          ls ./build/Darwin-arm64/install-Darwin
          cd ../METIS
          make config shared=1 prefix=./install-Darwin gklib_path=../GKLib/build/Darwin-arm64/install-Darwin i64=1 r64=1 VERBOSE=1 
          make install
          ls
          ls ./install-Darwin
          # mkdir build
          # cd build
          # cmake -DCMAKE_BUILD_TYPE=Release ../src
          # cmake --build .
