name: macos-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.8.0'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qt5compat qtcharts'
      - name: dependencies
        run: |
          brew update
          brew install boost
          brew install glfw3 
          brew install glew
      - name: build
        run: |
          cd external/GKlib && make config prefix=/Users/runner/work/PEMesh.2/PEMesh.2/external/GKlib/install-Linux && make && make install 
          cd ../METIS && make config shared=1 prefix=/Users/runner/work/PEMesh.2/PEMesh.2/external/METIS/install-Linux gklib_path=/Users/runner/work/PEMesh.2/PEMesh.2/external/GKlib/install-Linux i64=1 r64=1 VERBOSE=1 && make install
